spring:
  application:
    name: first-rest-with-spring-boot-and-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/first_rest_with_spring_boot_and_java?useTimezone=true&serverTimezone=UTC
    username: felipe
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false